
on: 
  push:
    tags: 
      - 'v20[0-9][0-9].[0-9][0-9].[0-9][0-9]'

jobs:
  build-and-release:
    name: Build And Release
    runs-on: [ ubuntu-latest ]
    steps:

      - name: 'Check Ref'
        if: github.ref != '/refs/heads/main'
        shell: bash
        run: echo "ERROR ! Workflow can only be run on main" && exit 1

      # https://github.com/marketplace/actions/checkout
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      # https://github.com/marketplace/actions/setup-python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9' 

      - name: Install Python, pipenv and Pipfile packages
        uses: kojoru/prepare-pipenv@v1

      - name: Unit Test
        shell: bash
        run: echo "TODO Add Unit Tests"

        
      - name: Build Wheel
        shell: bash
        run: python setup.py bdist_wheel 
        
      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          make_latest: true
          files: |
            'dist/**'